# AI Memory Extension - Dependabot Configuration
# Optimized for VS Code extension development with TypeScript

version: 2
updates:
  # NPM Dependencies (TypeScript/Node.js ecosystem)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
    # Group related updates to reduce PR noise
    groups:
      vscode-types:
        patterns:
          - "@types/vscode*"
          - "@vscode/*"
        applies-to: version-updates
      dev-tools:
        patterns:
          - "@biomejs/*"
          - "@rollup/*"
          - "@swc/*"
          - "rollup*"
          - "vite*"
          - "tsx"
          - "typescript"
        applies-to: version-updates
      testing:
        patterns:
          - "@vitest/*"
          - "vitest"
          - "cross-env"
        applies-to: version-updates
      production:
        patterns:
          - "@modelcontextprotocol/*"
          - "zod"
        applies-to: version-updates
    # Limit open PRs to keep things manageable
    open-pull-requests-limit: 5
    # Custom labels for better issue tracking
    labels:
      - "dependencies"
      - "npm"
      - "automerge-candidate"
    # Consistent commit messages
    commit-message:
      prefix: "deps"
      include: "scope"
    # Ignore major version updates for stable dependencies
    ignore:
      - dependency-name: "@types/vscode"
        update-types: ["version-update:semver-major"]
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]

  # GitHub Actions Updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "00:00"
    # Group all action updates together
    groups:
      actions:
        patterns:
          - "*"
        applies-to: version-updates
    open-pull-requests-limit: 2
    # Custom labels for better issue tracking
    labels:
      - "dependencies"
      - "github-actions"
      - "automerge-candidate"
    commit-message:
      prefix: "ci"
      include: "scope"
