# This workflow uses Biome for fast, modern linting and formatting
# Biome is a fast formatter and linter for JavaScript, TypeScript, JSX, and JSON
# More details at https://biomejs.dev

name: Code Quality (Biome)

on:
  push:
    branches: [ "main", "develop", "feature/**" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main", "develop" ]
  schedule:
    - cron: '41 10 * * 0'

jobs:
  biome:
    name: Run Biome checks
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run Biome checks (main extension)
        run: pnpm run lint

      - name: Run Biome checks (webview)
        run: cd src/webview && pnpm run lint

      - name: Check TypeScript types
        run: pnpm run check-types

      - name: Test build
        run: pnpm run build

      - name: Run tests with coverage
        run: |
          cd src/webview && pnpm run test:coverage
          cd ../..

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./src/webview/coverage/lcov.info
          flags: webview
          name: webview-coverage
        continue-on-error: true
